runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /(.*)\.(html|js|json|css)
  static_files: \1.\2
  upload: (.*)\.(html|js|json|css)

- url: /
  static_files: index.html
  upload: index\.html
  http_headers:
    Link: '</scripts/app.js>; rel=preload; as=script, </elements/gdgspain-app/gdgspain-app.html>; rel=preload; as=document, </styles/main.css>; rel=preload; as=style'
    # Access-Control-Allow-Origin: "*"

- url: /.*
  static_files: 404.html
  upload: 404\.html

skip_files:
- ^(.*/)?app\.yaml
